// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package main

import (
	"database/sql"
)

type Account struct {
	ID             int64        `json:"id"`
	DocumentNumber int64        `json:"document_number"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type OperationType struct {
	ID          int64        `json:"id"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Transaction struct {
	ID              int64        `json:"id"`
	AccountID       int32        `json:"account_id"`
	OperationTypeID int32        `json:"operation_type_id"`
	Amount          int64        `json:"amount"`
	EventDate       sql.NullTime `json:"event_date"`
}
