// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package database

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, documentNumber string) (Account, error)
	CreateOperationType(ctx context.Context, arg CreateOperationTypeParams) (OperationType, error)
	CreateTransactions(ctx context.Context, arg CreateTransactionsParams) (Transaction, error)
	DropAccount(ctx context.Context, id int64) error
	DropOperationType(ctx context.Context, id int64) error
	DropTransaction(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetOperationTypes(ctx context.Context, id int64) (OperationType, error)
	GetTransactions(ctx context.Context, id int64) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
