// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package main

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, documentNumber int64) (Account, error)
	CreateTransactions(ctx context.Context, arg CreateTransactionsParams) (Transaction, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetTransactions(ctx context.Context, id int64) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
